# Generated by Django 5.1.7 on 2025-03-09 21:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_nev', models.CharField(max_length=100)),
                ('v_nev', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['v_nev', 'k_nev'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Adja meg a műfajt...', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Írjon rövid összefoglalást a könyvhöz...', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character ISBN number', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='Az ISBN csak számokat tartalmazhat...')], verbose_name='ISBN')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='static/static_dirs')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author')),
                ('category', models.ManyToManyField(help_text='Válasszon műfajokat a könyvhöz...', to='books.category')),
            ],
            options={
                'ordering': ['title', 'author', 'description', 'cover_image', 'isbn'],
            },
        ),
    ]
