# Generated by Django 5.1.7 on 2025-03-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.CharField(blank=True, null=True, verbose_name='Születési év'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.CharField(blank=True, null=True, verbose_name='Halálának éve'),
        ),
        migrations.AlterField(
            model_name='author',
            name='k_nev',
            field=models.CharField(max_length=100, verbose_name='Keresztnév'),
        ),
        migrations.AlterField(
            model_name='author',
            name='v_nev',
            field=models.CharField(max_length=100, verbose_name='Vezetéknév'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Adja meg a műfajt...', max_length=100, verbose_name='Műfaj'),
        ),
    ]
