# Generated by Django 5.1.7 on 2025-03-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookcopy_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['v_nev', 'k_nev'], 'verbose_name': 'Műfaj', 'verbose_name_plural': 'Műfajok'},
        ),
    ]
