# Generated by Django 5.1.7 on 2025-03-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['v_nev', 'k_nev'], 'verbose_name': 'Szerző', 'verbose_name_plural': 'Szerzők'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author', 'description', 'cover_image', 'isbn'], 'verbose_name': 'Könyv', 'verbose_name_plural': 'Könyvek'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Műfaj', 'verbose_name_plural': 'Műfajok'},
        ),
    ]
