# Generated by Django 5.1.7 on 2025-03-10 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_author_options_alter_book_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'ordering': ['due_back'], 'verbose_name': 'Könyv példány', 'verbose_name_plural': 'Könyv példányok'},
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='books.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='borrowing_date',
            field=models.DateField(blank=True, help_text='When this copy was borrowed', null=True),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('u', 'Unavailable'), ('a', 'Available'), ('r', 'Reserved'), ('b', 'Borrowed'), ('d', 'Due Back')], default='a', help_text='Copy availability status', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 karakteres ISBN szám', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', message='Az ISBN csak számokat tartalmazhat...')], verbose_name='ISBN'),
        ),
    ]
