# Generated by Django 5.1.7 on 2025-03-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_bookcopy_options_bookcopy_book_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.CharField(null=True, verbose_name='Születési év'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='borrowing_date',
            field=models.DateField(blank=True, help_text='Mikor lett kikölcsönözésre átadva a könyv...', null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='due_back',
            field=models.DateField(blank=True, help_text='Mikorra kell visszahozni a kikölcsönzött könyvet...', null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('e', 'Elérhető'), ('f', 'Foglalt'), ('k', 'Kikölcsönözve'), ('v', 'Visszahozatal sürgősen')], default='e', help_text='Példány állapota.', max_length=1),
        ),
    ]
