# Generated by Django 5.1.7 on 2025-03-16 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_author_date_of_birth_alter_bookcopy_borrower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author', 'page_number', 'description', 'cover_image', 'isbn'], 'verbose_name': 'Könyv', 'verbose_name_plural': 'Könyvek'},
        ),
        migrations.AddField(
            model_name='book',
            name='page_number',
            field=models.CharField(default=1, max_length=4, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Oldalak száma'),
            preserve_default=False,
        ),
    ]
