# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_options_book_page_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'verbose_name': 'Könyv példány', 'verbose_name_plural': 'Könyv példányok'},
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='borrowing_date',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='due_back',
        ),
    ]
