# Generated by Django 5.1.7 on 2025-03-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookcopy_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
