# Generated by Django 5.1.7 on 2025-03-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_author_biography_remove_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
