# Generated by Django 5.1.7 on 2025-03-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_bookcopy_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('e', 'Elérhető'), ('f', 'Foglalt'), ('k', 'Kikölcsönözve'), ('v', 'VISSZAHOZATAL SÜRGŐSEN!')], default='e', help_text='Példány állapota.', max_length=1),
        ),
    ]
