# Generated by Django 5.1.7 on 2025-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Írjon rövid összefoglalást a könyvhöz... Max. 2000 karakter', max_length=1000),
        ),
    ]
