# Generated by Django 5.1.7 on 2025-04-19 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.author', verbose_name='Szerző'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(help_text='Válasszon műfajokat a könyvhöz...', to='books.category', verbose_name='Műfaj'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book-covers', verbose_name='Borítókép'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(help_text='Írjon rövid összefoglalást a könyvhöz... Max. 2000 karakter', max_length=2000, verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Cím'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowers', to=settings.AUTH_USER_MODEL, verbose_name='Kölcsönző felhasználó'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('e', 'Elérhető'), ('f', 'Foglalt'), ('k', 'Kikölcsönözve'), ('v', 'VISSZAHOZATAL SÜRGŐSEN!')], default='e', help_text='Példány állapota.', max_length=1, verbose_name='Állapot'),
        ),
    ]
