# Generated by Django 5.1.7 on 2025-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_bookcopy_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image_file_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
