# Generated by Django 5.1.7 on 2025-04-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_book_cover_image_file_id_book_cover_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_file_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image_path',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Borítókép URL'),
        ),
    ]
