# Generated by Django 5.1.7 on 2025-04-26 15:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_remove_book_cover_image_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image_url',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Borítókép'),
        ),
    ]
