# Generated by Django 5.1.7 on 2025-04-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_updated_at_alter_review_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vélemény', 'verbose_name_plural': 'Vélemények'},
        ),
    ]
