# Generated by Django 5.1.7 on 2025-04-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Értékelés', 'verbose_name_plural': 'Értékelések'},
        ),
    ]
