# Generated by Django 5.1.7 on 2025-03-25 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowinglistitem',
            name='list',
        ),
        migrations.AddField(
            model_name='borrowinglistitem',
            name='borrowing_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='list_item', to='borrow.borrowinglist'),
            preserve_default=False,
        ),
    ]
