# Generated by Django 5.1.7 on 2025-03-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrowinglist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='list',
            new_name='borrowing_list',
        ),
    ]
