# Generated by Django 5.1.7 on 2025-03-25 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_rename_list_borrowing_borrowing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedBorrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'KÖLCSÖNZÉS',
                'verbose_name_plural': 'KÖLCSÖNZÉSEK',
            },
        ),
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-borrow_date'], 'verbose_name': 'Kölcsönzési kérés', 'verbose_name_plural': 'Kölcsönzési kérések'},
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='borrowinglist',
            name='created_at',
        ),
    ]
