# Generated by Django 5.1.7 on 2025-03-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_verifiedborrowing_alter_borrowing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrow.borrowinglist'),
        ),
    ]
