# Generated by Django 5.1.7 on 2025-03-25 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_alter_borrowing_borrowing_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifiedborrowing',
            options={'ordering': ['-borrow_date'], 'verbose_name': 'KÖLCSÖNZÉS', 'verbose_name_plural': 'KÖLCSÖNZÉSEK'},
        ),
        migrations.RemoveField(
            model_name='borrowing',
            name='return_date',
        ),
        migrations.AddField(
            model_name='borrowinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifiedborrowing',
            name='borrowing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrow.borrowinglist'),
        ),
        migrations.AddField(
            model_name='verifiedborrowing',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
