# Generated by Django 5.1.7 on 2025-03-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_options_book_page_number'),
        ('borrow', '0007_alter_verifiedborrowing_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
