# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_bookcopy_options_and_more'),
        ('borrow', '0008_remove_borrowing_book_borrowing_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='books',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='book_copies',
            field=models.ManyToManyField(to='books.bookcopy'),
        ),
    ]
