# Generated by Django 5.1.7 on 2025-03-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0009_remove_borrowing_books_borrowing_book_copies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='borrowing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verifiedborrowing',
            name='borrowing',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verified_borrowing', to='borrow.borrowing'),
            preserve_default=False,
        ),
    ]
