# Generated by Django 5.1.7 on 2025-03-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0010_borrowhistory_borrowing_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedborrowing',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
