# Generated by Django 5.1.7 on 2025-03-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0011_verifiedborrowing_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='due_date',
            field=models.DateField(),
        ),
    ]
