# Generated by Django 5.1.7 on 2025-03-31 16:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_bookcopy_status'),
        ('borrow', '0012_alter_verifiedborrowing_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowhistory',
            options={'ordering': ['-return_date'], 'verbose_name': 'Kölcsönzési előzmény', 'verbose_name_plural': 'Kölcsönzési előzmények'},
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 31, 16, 27, 45, 624155, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 16, 28, 0, 200343, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_borrow_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
