# Generated by Django 5.1.7 on 2025-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_alter_bookcopy_status'),
        ('borrow', '0013_alter_borrowhistory_options_borrowhistory_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowhistory',
            name='book',
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='book_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='borrowhistory',
            name='books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
