# Generated by Django 5.1.7 on 2025-03-31 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0014_remove_borrowhistory_book_borrowhistory_book_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
