# Generated by Django 5.1.7 on 2025-03-31 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0016_alter_borrowing_borrowing_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='borrow.borrowinglist'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='borrowing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrow.borrowinglist'),
        ),
    ]
