# Generated by Django 5.1.7 on 2025-03-31 19:57

import borrow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0018_alter_borrowing_borrowing_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowhistory',
            options={'ordering': ['-return_date'], 'verbose_name': '3. Kölcsönzési előzmény', 'verbose_name_plural': '3. Kölcsönzési előzmények'},
        ),
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-borrow_date'], 'verbose_name': '1. Kölcsönzési kérés', 'verbose_name_plural': '1. Kölcsönzési kérések'},
        ),
        migrations.AlterModelOptions(
            name='verifiedborrowing',
            options={'ordering': ['-borrow_date'], 'verbose_name': '2. KÖLCSÖNZÉS', 'verbose_name_plural': '2. KÖLCSÖNZÉSEK'},
        ),
        migrations.AddField(
            model_name='borrowing',
            name='expire_date',
            field=models.DateTimeField(default=borrow.models.Borrowing.get_expire_date),
        ),
    ]
