# Generated by Django 5.1.7 on 2025-03-31 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0019_alter_borrowhistory_options_alter_borrowing_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedborrowing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='verified_borrowing', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
