# Generated by Django 5.1.7 on 2025-04-03 14:23

import borrow.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0020_verifiedborrowing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='expire_date',
            field=models.DateField(default=borrow.models.Borrowing.get_expire_date),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
