# Generated by Django 5.1.7 on 2025-04-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0021_alter_borrowing_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowhistory',
            name='return_date',
            field=models.DateField(),
        ),
    ]
