# Generated by Django 5.1.7 on 2025-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_alter_book_description'),
        ('borrow', '0022_alter_borrowhistory_return_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowing',
            options={'ordering': ['-borrow_date'], 'verbose_name': '1. Kölcsönzési igénylés', 'verbose_name_plural': '1. Kölcsönzési igénylések'},
        ),
        migrations.AlterModelOptions(
            name='verifiedborrowing',
            options={'ordering': ['-borrow_date'], 'verbose_name': '2. Folyamatban lévő kölcsönzés', 'verbose_name_plural': '2. Folyamatban lévő kölcsönzések'},
        ),
        migrations.AddField(
            model_name='verifiedborrowing',
            name='book_copies',
            field=models.ManyToManyField(to='books.bookcopy'),
        ),
    ]
