# Generated by Django 5.1.7 on 2025-04-19 17:04

import borrow.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_author_alter_book_category_and_more'),
        ('borrow', '0023_alter_borrowing_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowhistory',
            name='book_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Könyvek száma'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='books',
            field=models.ManyToManyField(to='books.book', verbose_name='Könyvek'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='due_date',
            field=models.DateField(verbose_name='Visszahozatal határideje'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='return_date',
            field=models.DateField(verbose_name='Visszahozatal ideje'),
        ),
        migrations.AlterField(
            model_name='borrowhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_history', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='book_copies',
            field=models.ManyToManyField(to='books.bookcopy', verbose_name='Könyv példányok'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Igénylés ideje'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrow.borrowinglist', verbose_name='Igénylés ID'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='expire_date',
            field=models.DateField(default=borrow.models.Borrowing.get_expire_date, verbose_name='Határidő elvitelre'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='KÖLCSÖNZÉS JÓVÁHAGYÁSA'),
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowing', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='book_copies',
            field=models.ManyToManyField(to='books.bookcopy', verbose_name='Könyv példányok'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kikölcsönzés ideje'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='borrowing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_borrowing', to='borrow.borrowing', verbose_name='Kölcsönzés ID'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='borrowing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='borrow.borrowinglist', verbose_name='Igénylés ID'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='due_date',
            field=models.DateField(verbose_name='Határidő visszahozatalra'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='VISSZAHOZVA'),
        ),
        migrations.AlterField(
            model_name='verifiedborrowing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_borrowing', to=settings.AUTH_USER_MODEL, verbose_name='Felhasználó'),
        ),
    ]
