# Generated by Django 5.1.7 on 2025-04-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kívánságlista', 'verbose_name_plural': 'Kívánságlisták'},
        ),
    ]
